name: Register_customer_environment
values:
  - key: username
    value: ''
  - key: email
    value: ''
  - key: password
    value: ''
  - key: refresh_token
    value: ''
  - key: access_token
    value: ''
  - key: new_category_name
    value: ''
