# Generated by Django 6.0.4 on 2026-06-20 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=False)),
                ('provider_token', models.CharField(max_length=255)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('card', 'Card'), ('bank', 'Bank'), ('wallet', 'Wallet')], max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('provider', models.CharField(max_length=15)),
            ],
            options={
                'unique_together': {('type', 'name', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('paymentstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.paymentstrategy')),
                ('bank_name', models.CharField(max_length=15)),
                ('last_4_digits', models.CharField(max_length=4)),
                ('time_of_verification', models.DateField(blank=True, default=None, null=True)),
            ],
            bases=('payment.paymentstrategy',),
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('paymentstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.paymentstrategy')),
                ('network', models.CharField(max_length=15)),
                ('last_4_digits', models.CharField(max_length=4)),
                ('expiry_date', models.DateField()),
                ('card_owner_name', models.CharField(max_length=63)),
            ],
            bases=('payment.paymentstrategy',),
        ),
        migrations.CreateModel(
            name='WalletPayment',
            fields=[
                ('paymentstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.paymentstrategy')),
                ('type', models.CharField(choices=[('balance', 'Balance'), ('Bank linked', 'Bank linked'), ('Tokenized card', 'Tokenized card'), ('BNPL', 'Buy now, pay Later')], max_length=15)),
                ('provider', models.CharField(choices=[('balance', 'Balance'), ('Bank linked', 'Bank linked'), ('Tokenized card', 'Tokenized card'), ('BNPL', 'Buy now, pay Later')], max_length=15)),
                ('email', models.EmailField(max_length=63)),
                ('external_account_id', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
            ],
            bases=('payment.paymentstrategy',),
        ),
        migrations.AddField(
            model_name='paymentstrategy',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod'),
        ),
    ]
