# Generated by Django 6.0.4 on 2026-06-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.CharField(max_length=127, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('datasheet', models.JSONField()),
                ('timeOfCreation', models.DateTimeField()),
                ('timeOfDeletion', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('barcode', models.CharField(max_length=127, primary_key=True, serialize=False, unique=True)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priceCurrency', models.CharField(max_length=3)),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('attribute', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=63)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('unitPrice__gte', 0)), name='unit_price_non_negative'),
        ),
    ]
