# Generated by Django 6.0.4 on 2026-06-10 14:14
from django.db import migrations
from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.models import ContentType
from users.models.user.roles import Role
from django.contrib.auth.models import Group, Permission
from django.db import models

from typing import Type, List

class GroupPermission:
    def __init__(
            self,
            group: str,
            permissions: List[str],
    ):
        self.group = group
        self.permissions = permissions

    def apply(self, model: Type[models.Model], content_type: ContentType, Group: Type[Group], Permission: Type[Permission]):
        group = Group.objects.get(name=self.group)

        permissions = list()
        for permission in self.permissions:
            permissions.append(f"{permission}_{model._meta.model_name}")

        permissions_models = Permission.objects.filter(
            content_type = content_type,
            codename__in = permissions
        )

        group.permissions.add(*permissions_models)


    def remove(self, model, content_type, Group: Type[Group], Permission: Type[Permission]):
        group = Group.objects.get(name=self.group)

        permissions = list()
        for permission in self.permissions:
            permissions.append(f"{permission}_{model._meta.model_name}")

        permission_models = Permission.objects.filter(content_type=content_type, codename__in=permissions)

        group.permissions.remove(*permission_models)


class ModelContent:
    def __init__(
            self,
            model: Type[models.Model],
            content_type: ContentType,
    ):
        self.model = model
        self.content_type = content_type



def create_groups_permissions(apps, schema_editor):
    create_permissions(global_apps.get_app_config('catalog'), verbosity=0, apps=apps)


    product = apps.get_model("catalog", "Product")
    product_variant = apps.get_model("catalog", "ProductVariant")
    product_attribute = apps.get_model("catalog", "ProductAttribute")
    categories = apps.get_model("catalog", "Category")

    ContentType = apps.get_model("contenttypes", "ContentType")

    models_to_alter = [
        ModelContent(
            model=product,
            content_type= ContentType.objects.get_for_model(product)
        ),

        ModelContent(
            model=product_variant,
            content_type= ContentType.objects.get_for_model(product_variant)
        ),

        ModelContent(
            model=product_attribute,
            content_type=ContentType.objects.get_for_model(product_attribute)
        ),

        ModelContent(
            model=categories,
            content_type= ContentType.objects.get_for_model(categories)
        )
    ]

    product_permissions = {
        Role.webmaster: ['view', 'change', 'delete', 'add'],
        Role.staff: ['view', 'change', 'delete', 'add'],
        Role.customer: ['view'],
    }

    for role in product_permissions:
        permissions_for_this_role = product_permissions[role]

        permissions_model = GroupPermission(
            group=role,
            permissions=permissions_for_this_role
        )

        Group = apps.get_model("auth", "Group")
        Permission = apps.get_model("auth", "Permission")

        for model in models_to_alter:
            permissions_model.apply(
                model = model.model,
                content_type = model.content_type,
                Group = Group,
                Permission = Permission,
            )


def reverse_migration(apps, schema_editor):
    product = apps.get_model('catalog', 'Product')
    product_variant = apps.get_model('catalog', 'ProductVariant')
    product_attributes = apps.get_model('catalog', 'ProductAttribute')
    category = apps.get_model("catalog", "Category")

    models_to_alter = [
        product, product_variant, product_attributes, category
    ]

    product_permissions = {
        Role.webmaster: ['view', 'change', 'delete', 'add'],
        Role.staff: ['view', 'change', 'delete', 'add'],
        Role.customer: ['view'],
    }

    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for model in models_to_alter:
        content_type_for_this_model = ContentType.objects.get_for_model(model)

        for role, permission in product_permissions.items():
            permissions_for_this_group = GroupPermission(
                group=role,
                permissions=permission
            )

            permissions_for_this_group.remove(
                model=model,
                content_type=content_type_for_this_model,
                Group=Group,
                Permission=Permission
            )


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ('users', '0001_create_groups'),
        ('catalog', '0001_make_products_models')
    ]

    operations = [
        migrations.RunPython(create_groups_permissions, reverse_migration),
    ]
