# Generated by Django 6.0.4 on 2026-06-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_permissions_for_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='timeOfDeletion',
            field=models.DateTimeField(null=True),
        ),
    ]
