# Generated by Django 6.0.4 on 2026-06-21 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_datasheet_alter_product_timeofdeletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requires_confirmation', "Waiting for confirmation on staff's end"), ('paid', 'Order paid'), ('processing', 'Order paid and waiting for shipment'), ('shipped', 'Order shipped'), ('succeeded', 'Order was delivered successfully'), ('canceled', 'Order canceled'), ('action_required', "Requested action on user's end"), ('refund_requested', 'Customer requested refund'), ('refunded', 'Customer refunded')], default='requires_confirmation', max_length=21)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('shipping_street', models.CharField(max_length=127)),
                ('street_zipcode', models.CharField(max_length=10)),
                ('shipping_municipality', models.CharField(max_length=31)),
                ('shipping_country', models.CharField(max_length=2)),
                ('time_of_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='order_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('ordered_item_surrogate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_ordered', models.IntegerField()),
                ('unit_price_at_purchase_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price_at_purchase_time__gt', 0)), name='unit_price_at_purchase_time_non_negative'), models.UniqueConstraint(fields=('product', 'order'), name='ordered_item_actual_pk_product_order')],
            },
        ),
    ]
