# Generated by Django 6.0.4 on 2026-06-25 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_hash',
            field=models.CharField(db_index=True, default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_token__isnull', True), ('user__isnull', False)), models.Q(('guest_token__isnull', False), ('user__isnull', True)), _connector='OR'), name='no_duplicate_identity_for_user'),
        ),

        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION copy_email_for_authenticated_user() RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.user_id IS NOT NULL THEN
                    SELECT email INTO NEW.email FROM auth_user WHERE id = NEW.user_id;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER sync_user_email_for_order
            BEFORE INSERT OR UPDATE ON order_order
            FOR EACH ROW EXECUTE FUNCTION copy_email_for_authenticated_user();
        """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS sync_user_email_for_order ON order_order;
            DROP FUNCTION IF EXISTS copy_email_for_authenticated_user();
        """,
        ),

    ]
