# Generated by Django 6.0.4 on 2026-07-09 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart_hash_order_email_order_guest_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_hash',
            field=models.CharField(db_index=True, default=None, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['canceled', 'refunded']), _negated=True), fields=('cart_hash', 'user'), name='one_active_order_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['canceled', 'refunded']), _negated=True), fields=('cart_hash', 'guest_token'), name='one_active_order_per_guest_cart'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('cart_hash__isnull', True), ('cart_hash__length', 64), _connector='OR'), name='cart_hash_null_or_64_chars'),
        ),
    ]
