# Generated by Django 6.0.4 on 2026-07-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_cart_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requires_confirmation', "Waiting for confirmation on staff's end"), ('waiting_for_payment', "Waiting for payment on staff's end"), ('paid', 'Order paid'), ('processing', 'Order paid and waiting for shipment'), ('shipped', 'Order shipped'), ('succeeded', 'Order was delivered successfully'), ('canceled', 'Order canceled'), ('action_required', "Requested action on user's end"), ('refund_requested', 'Customer requested refund'), ('refunded', 'Customer refunded')], default='requires_confirmation', max_length=21),
        ),
    ]
